### ISSUE TITLE
Integration assets and manifest updates

### ISSUE THREAD

**Issue by macf0x** [funtastix/rinnaitouch#12]
Hi,

There's a couple of linkages that might be beneficial to getting feedback on this integration and expanding uptake.

Adding the Diagnostics exports to the integration, to assist with debugging.
https://www.home-assistant.io/integrations/diagnostics/

Also updating the manifest so it points the repo, so users can submit issues, rather than via the forum.
https://developers.home-assistant.io/docs/creating_integration_manifest/

And Logo
https://commons.wikimedia.org/wiki/File:Rinnai_Logo_2019.png
https://commons.wikimedia.org/wiki/File:Rinnai.svg

**Comment by funtastix** [comment]
How is that logo added? I think it needs to be committed to a special repo? The other ones can go on the todo list.

**Comment by macf0x** [comment]
Correct you need to add to https://github.com/home-assistant/brands

They have branding for core and custom_integrations

ie. https://brands.home-assistant.io/rinnaitouch/dark_icon.png

**Comment by funtastix** [comment]
Only diagnostics left on this list. There's an issue with the icons after they got merged, but working on that.

Note: master and develop are now HACS compatible. That will likely break the next pull. I've added a new step in the installation instructions to move the files.
