### ISSUE TITLE
Evap fan speed

### ISSUE THREAD

**Issue by reesion** [funtastix/rinnaitouch#21]
Hi,

Is there a way to adjust the fan speed? 

The fan mode shows once I turned on the Evap but it only have the on/off switch. It doesn't show the fan speed.

Thank you.

**Comment by funtastix** [comment]
I've got fan control still on my list, but currently focusing on getting the integration working with a few people's setups, especially with zones (I don't have any, so doing this a bit blind).

Having said that, in evap you should have control in manual mode only:
- for Auto mode (the calendar symbol with two arrows) you can set the comfort level (19-35 or so)
- for Manual mode (just the two arrows) in on, the climate control for a normal climate lovelace card should switch to controlling fan speed.

As said, my plan is to make a separate fan entity to control the fan, also when it's in fan only mode for heating.

Can you confirm that works as described?

**Comment by reesion** [comment]
> Can you confirm that works as described?

Yes, i can confirm that's the case.

![image](https://user-images.githubusercontent.com/53692597/157436159-7bd86784-3f50-4ce9-b930-63c1c1d2173f.png)

Above is what i see for manual mode. Is the dial (3/4 circle) the control of the fan speed?

**Comment by funtastix** [comment]
That's correct. The dial is at 15. The highest speed is 16, so I'm going to assume your fan is on quite a high setting.

**Comment by reesion** [comment]
Ok thanks. I normally set it to around 75% which was 14

**Comment by funtastix** [comment]
That's great. I need to find time to write some documentation I think
