### ISSUE TITLE
Water Pump Switch Disappeared

### ISSUE THREAD

**Issue by jackielegs98** [funtastix/rinnaitouch#36]
I have just updated to 0.9.0 from HACS as this will make it easier to update in the future. I deleted the integration and custom repository and reinstalled from scratch.

After adding the integration I've found that the water pump switch for the evaporative cooling isn't showing up.

My Setup:
NC6 with heating and evaporative cooling - no zones

![Screen Shot 2022-03-14 at 16 28 09](https://user-images.githubusercontent.com/80939121/158110249-847f483a-856a-4b80-82fb-6ae2f6e0b35c.png)

**Comment by funtastix** [comment]
That's exactly like my setup. I deleted, restarted, added HACS, then restarted again, and all worked, including the water pump. Could you remove, restart, and re-add and see if there is anything in the logs when the integration is added?

**Comment by jackielegs98** [comment]
Had done it a few times, but then walked away and came back a few hours later and it was there!
