### ISSUE TITLE
Can't control evap speed

### ISSUE THREAD

**Issue by jackielegs98** [funtastix/rinnaitouch#41]
Hi again,

after some of the latest updates (unsure which one exactly) I can no longer control the fan speed at all when set to "heat/cool" -> "evap". Instead I get this alert and the fan speed doesn't change:

![image](https://user-images.githubusercontent.com/80939121/159145027-7fae2d2f-6ea1-4aa5-8117-059704f59242.jpeg)

I also can't change from heat/cool -> auto mode because the water pump doesn't appear after re-setting up the integration, and I get this error:

<img width="726" alt="Screen Shot 2022-03-20 at 13 08 54" src="https://user-images.githubusercontent.com/80939121/159144968-6dba14d3-0243-43c2-810f-2394cd0d3063.png">

BUT once I change the mode to auto on the NC6 itself, I can set the "comfort level" temperature or set the heating temperature

Also, somewhere along the way I've lost the ability to set the "fan mode" control section and can no longer set it to fan only:

<img width="418" alt="Screen Shot 2022-03-20 at 13 03 56" src="https://user-images.githubusercontent.com/80939121/159144855-e3ebb239-8762-4606-9df8-acf494798576.png">

**Comment by funtastix** [comment]
Can you try again with https://github.com/funtastix/rinnaitouch/releases/tag/0.9.3 ?

Should fix the fan speed at least.

The water pump one I cannot fully understand. Are there any steps to reproduce this?

For the fan only mode, it can only be turned on when NOT in EVAP preset. Ideally though, you would use the Circ Fan switch instead, and in Evap mode the water pump and fan switches (i.e. turn the water pump off for EVAP fan only mode). The difference is that in EVAP fan mode (water pump off) the air comes through the cooling vents, in heater fan only mode, it comes through the heating vents.

**Comment by funtastix** [comment]
Btw, one thing I did notice is that after removing and re-adding the integration without a restart, the entity IDs get a "_2" in the name. Could this be the water pump problem root cause?

**Comment by jackielegs98** [comment]
Fan speed was fixed with 0.9.3 thank you!

The way I have the climate card I'm using set up is as you've described. In heat/cool (manual) -> EVAP mode you can control the fan speed between 1 and 16 and the water pump presents as a switch that you can turn on and turn off.

To recreate:
Deleted Integration
Restarted HA
Put system into 'AUTO' mode
Re-added integration
All expected entities were exposed including water pump switch - however the entity was 'unavailable'

Put system into manual EVAP mode - water pump entity still unavailable

Turn on water pump on physical NC6 controller
Reload integration
Integration states: "Retrying setup: no specified entity for Rinnai Touch Water Pump Switch"

Turn system back to 'AUTO' mode
Reload integration
All entities restored including water pump but it remains 'unavailable'

**Comment by funtastix** [comment]
Water pump entity should only be available in manual evap mode, and it could take up to 10 seconds to become available.

All entities register with the main system for updates, I have not actually tested reloading the integration much, as I usually start HA to get my entity names back clean.

After your last step, back in auto mode, when you then switch to Manual, either on the NC6 or HA, without reload, does the switch become available?

**Comment by funtastix** [comment]
Found one more issue. It seems reloading doesn't affect the behaviour, it still breaks. 

Try with https://github.com/funtastix/rinnaitouch/releases/tag/0.9.4

**Comment by funtastix** [comment]
You may need a HA restart for the fix to work.

**Comment by jackielegs98** [comment]
0.9.4 seems to have fixed it!

When the system is off or is in certain modes irrelevant entities are 'unavailable'. When you change to a different mode the relevant entities become available after a few seconds.

**Comment by funtastix** [comment]
That is correct, only entities relevant to the current system state are available.
