### ISSUE TITLE
No GSO when heater on. Not haapy, Jan

### ISSUE THREAD

**Issue by GraceO77** [funtastix/rinnaitouch#48]
Seeing consistent error in logs. Also seems to be slowing HA down when integration is installed. with scripts and automations triggering much slower across all of HA. 

Any ideas on solution? 

![Screenshot 2022-10-23 124231](https://user-images.githubusercontent.com/53988901/197369137-b80cb252-dc2d-4c30-8b2c-d9c94f521e78.jpg)

**Comment by funtastix** [comment]
Try with 0.11.3. These issues should now be fixed
