### ISSUE TITLE
Integration setup - 3rd unlabelled field

### ISSUE THREAD

**Issue by macf0x** [funtastix/rinnaitouch#5]
During integration setup you are prompted to a blank field

Does this need to be populated with some value?

![brivis](https://user-images.githubusercontent.com/21240188/154780888-7ba1c516-f075-4cb7-9755-cb3ec8a86746.jpg)

**Comment by macf0x** [comment]
That solves the mystery. I was trying to work out where to add that.

Just testing the expose_entity branch.

**Comment by funtastix** [comment]
That should be fixed.
