### ISSUE TITLE
Is there a way to report the evap fan speed

### ISSUE THREAD

**Issue by rwhitby** [funtastix/rinnaitouch#50]
I'd like to write an automation which takes into account the outside temperature and humidity (Aqara sensor) and the inside temperature and humidity (another Aqara sensor) and the current fan speed and adjust the comfort level in AUTO mode.

It looks like the underlying python library can extract the current fan speed from the status updates. Is it possible to expose that current fan speed as a sensor?

**Comment by funtastix** [comment]
I checked that a while ago, but forgot to respond. Unfortunately, the fan speed is not reported back. I think I had the same thought when I initially did the module, but it's just not reported, same as the temperature is never reported back, sadly.
