### ISSUE TITLE
Issue with latest version

### ISSUE THREAD

**Issue by galapogos01** [funtastix/rinnaitouch#51]
Hey @funtastix 

First up thanks heaps for supporting the community with this awesome Integration :slight_smile:

I raised this originally at https://community.home-assistant.io/t/rinnai-heating-cooling-wifi-module/109908/746?u=jbolger

I have a 3-zone setup with refrig AC. The way I use the setup is mostly in Auto mode, occasionally setting custom temps but mostly turning the master Heat/Cool/Fan control on/off and letting the schedule do its thing.

I have added the integration however the controls don’t seem to do anything. Nothing is in sync with the actual unit - HA is displaying actual mode & room temp, but set point temp is 0, and sending any Heat/Cool/Fan/Temp commands does nothing. It all works fine via the Rinnai Touch app.

In the Core log I get loads of

`2023-01-18 07:10:19.176 ERROR (MainThread) [pyrinnaitouch.cooler] No GSO when cooling on. Not happy, Jan`

The debug log shows the command sending & the mylink responding but as mentioned no change on the unit

`2023-01-18 14:20:48.086 DEBUG (MainThread) [pyrinnaitouch.system] Sending command: N000002{"CGOM": {"OOP": {"ST": "Z" } } }
2023-01-18 14:20:51.086 DEBUG (MainThread) [pyrinnaitouch.system] Sequence: 3 Json: [{"SYST": {"CFG": {"MTSP": "Y", "NC": "00", "DF": "N", "TU": "C", "CF": "1", "VR": "0183", "CV": "0010", "CC": "043", "ZA": "                ", "ZB": "                ", "ZC": "                ", "ZD": "                " }, "AVM": {"HG": "Y", "EC": "N", "CG": "Y", "RA": "N", "RH": "N", "RC": "N" }, "OSS": {"DY": "THU", "TM": "14:18", "BP": "Y", "RG": "Y", "ST": "N", "MD": "C", "DE": "N", "DU": "N", "AT": "999", "LO": "N" }, "FLT": {"AV": "N", "C3": "000" } } },{"CGOM": {"CFG": {"ZUIS": "N", "ZAIS": "Y", "ZBIS": "Y", "ZCIS": "Y", "ZDIS": "N", "CF": "N", "PS": "Y", "DG": "W" }, "OOP": {"ST": "Z", "CF": "N", "FL": "11", "SN": "N" }, "ZUO": {"UE": "N" }, "ZAO": {"UE": "Y" }, "ZBO": {"UE": "Y" }, "ZCO": {"UE": "Y" }, "ZDO": {"UE": "N" }, "ZUS": {"AE": "N", "MT": "241", "ID": "N", "CP": "N", "FS": "N" }, "ZAS": {"AE": "N", "MT": "229", "ID": "Y", "CP": "N", "FS": "N" }, "ZBS": {"AE": "N", "MT": "241", "ID": "Y", "CP": "N", "FS": "N" }, "ZCS": {"AE": "N", "MT": "233", "ID": "Y", "CP": "N", "FS": "N" }, "ZDS": {"AE": "N", "MT": "241", "ID": "N", "CP": "N", "FS": "N" }, "APZ": {"ZV": "N" } } }]
2023-01-18 14:20:51.086 DEBUG (MainThread) [pyrinnaitouch.cooler] Circulation Fan is: Z
2023-01-18 14:20:51.086 DEBUG (MainThread) [pyrinnaitouch.cooler] Fan Speed is: 11
`
Any tips on where to go from here?

Cheers, Jason

**Comment by funtastix** [comment]
Hi Jason,
This is the first multi set point enabled log I've ever come across. From what I can see, the integration doesn't support multi set point at this stage. I'd have to make a fair few amendments to support it, but it could be possible. I don't have the time to look into it this week, but possibly could try next week, but would need someone to be willing to go through some testing...
Cheers

**Comment by galapogos01** [comment]
Ah. I wrongly assumed all zoned setups must be multi set point.

Happy to support with whatever testing is required. 

Cheers,
Jason

**Comment by Alesum** [comment]
Hi @funtastix. I am also experiencing similar issues. Further details:

I have a Brivis system with heating and refrigerative cooling. 3 separate zones with 3 x NC-6 thermostat controllers - Master (which is also Zone A), Zone B and Zone C.
I have the Rinnai Touch WiFi kit setup successfully and App working on an android phone perfectly. Despite some people reporting that their NC-6s don’t report temperature through the Rinnai Touch app, mine does. Current temps are also reported through to your integration. See attached screenshot of the 3 zones in the Rinnai Touch App.

![image](https://user-images.githubusercontent.com/5343135/216573172-e3902119-f5e0-4421-ac7f-aabb69c15f1e.png)

I installed your integration via HACS on Home Assistant (running via Virtual Box on a spare PC). All 3 zones immediately show up and correctly report the current state (E.g. cooling on) and the correct current temperature of each of the 3 NC-6s. However, they show 0 degrees for the target temperature within the thermostats. Weirldy, each of the individual Zone Target Temperature Sensor cards report the target temperature. Screenshots attached.

![image](https://user-images.githubusercontent.com/5343135/216573502-d2c3cb5a-98c9-4953-be5b-21f05c254999.png)

This is where I hit a wall. The thermostats on the dashboard mostly show the correct information, but other than "Off" and "Fan Only" most controls fail to do anything and throw an error. I.e. if I try to adjust the target temperature the slider moves and the number displays, but it doesn’t actually do anything - it doesn’t take and doesn’t seem to send a command. If I try and change the mode from cooling to heating it doesn’t do anything etc.

There are two errors in the logs that I can see:

![image](https://user-images.githubusercontent.com/5343135/216573974-6cd5f209-3253-42ce-8c91-a4530340ba64.png)

and:

[139707032835008] RinnaiSystem.set_cooling_zone_temp() missing 1 required positional argument: ‘temp’
Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py”, line 200, in handle_call_service
await hass.services.async_call(
File “/usr/src/homeassistant/homeassistant/core.py”, line 1755, in async_call
task.result()
File “/usr/src/homeassistant/homeassistant/core.py”, line 1792, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File “/usr/src/homeassistant/homeassistant/helpers/entity_component.py”, line 213, in handle_service
await service.entity_service_call(
File “/usr/src/homeassistant/homeassistant/helpers/service.py”, line 678, in entity_service_call
future.result() # pop exception if have
File “/usr/src/homeassistant/homeassistant/helpers/entity.py”, line 958, in async_request_call
await coro
File “/usr/src/homeassistant/homeassistant/helpers/service.py”, line 715, in _handle_entity_call
await result
File “/usr/src/homeassistant/homeassistant/components/climate/init.py”, line 613, in async_service_temperature_set
await entity.async_set_temperature(**kwargs)
File “/config/custom_components/rinnaitouch/climate.py”, line 682, in async_set_temperature
await self.async_set_target_temperature(kwargs.get(ATTR_TEMPERATURE))
File “/config/custom_components/rinnaitouch/climate.py”, line 696, in async_set_target_temperature
await self._system.set_cooling_zone_temp(target_temperature)
TypeError: RinnaiSystem.set_cooling_zone_temp() missing 1 required positional argument: ‘temp’


I hope this makes sense - I am pretty green with Home Assistant and no nothing about coding/programming etc.

If you do get a chance to look into this I would be so grateful. It would be amazing to gain thermostat control via HA, and I am more than happy to do whatever testing you need to help. You'll just have to excuse my limited abilities.

Cheers,
Sam

**Comment by funtastix** [comment]
Just started looking at this. The logs above with JSON in it seem to show a unit in Fan Only mode. are you able to turn on debug mode, use the latest integration (0.11.4) and post some logs, ideally run until JSON appears, while cooling is on and target temperatures are set, then try to change the temperature.

turn debug logging on in your configuration.yaml:

`logger:
  default: warning
  logs:
    custom_components.rinnaitouch: debug
    custom_components.rinnaitouch.pyrinnaitouch: debug
    pyrinnaitouch: debug`

**Comment by Alesum** [comment]
Hi @funtastix - Thank you heaps for looking into this, especially as you don't use zones yourself. Really means a lot.

I updated to v0.11.4, turned debug logging on with your code in yaml, cleared logs and then with HVAC set to cooling tried changing the temp in a couple of the zones. Please find below a download of the logs. Hopefully this shows you what you are looking for...

[home-assistant_2023-02-07T12-59-55.321Z.log](https://github.com/funtastix/rinnaitouch/files/10675210/home-assistant_2023-02-07T12-59-55.321Z.log)

**Comment by funtastix** [comment]
So there's a fair but to do, still, but maybe not as bad as I thought.

I've created 0.11.5 to provide an immediate fix for setting zone temperature. This will not work for the common zone. It's still looking for GSO, which multi-setpoint does not have.

Notes for self:
- refactor zones into objects
- distinguish between GSO and common zone -- don't create main entity if there's no GSO, just zones and a common zone if it exists.
- add additional zone attributes for multi-setpoint

**Comment by Alesum** [comment]
Great. I can confirm that setting the temperature in each of the separate zones now works. As you can see in the below screenshot this does not display the set temperature in the thermostat and the slider returns to 0 after a period of time - However, I can confirm that the command works - The Touch WiFi app shows the adjusted temperature. In the below screenshot each of the 3 zones have cooling on and temperature is set to 22°, it just isn't displayed.

![image](https://user-images.githubusercontent.com/5343135/217458839-e8f0535e-1843-46ac-8855-55e85f9906a4.png)

**Comment by funtastix** [comment]
OK, so I've refactored and done a bit of testing with the states from your logs. I've created a branch https://github.com/funtastix/rinnaitouch/tree/zone_refactor that has that code with a beta version of the library. It's quite a big update, and I think zones probably didn't really work much before, there was a lot to tidy up.

Can you have test with that branch directly? I think you can point HACS to a branch AFAIK.

**Comment by Alesum** [comment]
Thank you @Fantastix! I'll give this a whirl in the next day or two and let you know.

**Comment by funtastix** [comment]
> Thank you @fantastix! I'll give this a whirl in the next day or two and let you know.

When you do, give the branch ```code_refactor``` a try instead. I've reorganised the code a fair bit and added a few more fixes along the way. See [here](https://github.com/funtastix/pyrinnaitouch/issues/8#issuecomment-1440907832)

**Comment by funtastix** [comment]
This is now released in 0.12.3 and testing as part of https://github.com/funtastix/pyrinnaitouch/issues/8
