### ISSUE TITLE
Incompatibility with HA 2023.3

### ISSUE THREAD

**Issue by rwhitby** [funtastix/rinnaitouch#52]
WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for rinnaitouch using this method at custom_components/rinnaitouch/__init__.py, line 47: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by rwhitby** [comment]
Not sure whether this is the cause or not, but Rinnai Touch has stopped working after updating to HA 2023.2

**Comment by funtastix** [comment]
It shouldn't be related. Is that the only issue in the log? I have fixed the icompatibility issue. Thanks for the report. Please try the latest release 0.11.0
