### ISSUE TITLE
Thermostat unavailable

### ISSUE THREAD

**Issue by nksoft** [funtastix/rinnaitouch#63]
I get these warning below when I restart home assistant (on 2023.2). Now the thermostat is unavailable and doesn't update state even when running. Official Rinnai touch app works. Thanks for the efforts you guys put into these. Much appreciated!

`Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 6:23:43 PM (1 occurrences)
Last logged: 6:23:43 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for rinnaitouch using this method at custom_components/rinnaitouch/__init__.py, line 47: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:605
Integration: Sensor (documentation, issues)
First occurred: 6:23:43 PM (2 occurrences)
Last logged: 6:23:43 PM

Sensor sensor.rinnai_touch_schedule_time_period_sensor has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: N/A (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.rinnai_touch_advance_time_period_sensor has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: N/A (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.`

**Comment by funtastix** [comment]
Have you tried with the latest version (0.11.6)? These should be fixed.

**Comment by nksoft** [comment]
I am so sorry, I didn't realise there were updates! Yes, those warnings are not coming up now, thank you! I think my controller is having issues :( I power cycled it last time when it was not working and now even on the official Rinnai Touch app it's stating "The System is Initialising..." forever.
