### ISSUE TITLE
Expose "working state" to Home Assistant?

### ISSUE THREAD

**Issue by nathbullen** [funtastix/rinnaitouch#66]
I'm probably using the wrong terminology, but when using the HomeBridge Plugin, it exposes the working state of the heater/cooler unit. I've noticed this integration doesn't expose the same information to Home Assistant - I was just wondering if it was possible for a future version of this integration?

This is less important for the evap cooling mode imho but helpful for heat, because you can see on the temperature graph when the heater was actively heating, vs when it is set to heat but just idle. Here's a few random screenshots from the internet to better illustrate my badly explained point:

![image](https://user-images.githubusercontent.com/63625786/220803809-237dcb14-22e8-4b77-ad92-f34014fa8614.png)
![image](https://user-images.githubusercontent.com/63625786/220803873-14e43ee3-1fe7-4ed1-b12b-9e7f68db4b14.png)

**Comment by funtastix** [comment]
I can see a few things that can be utilised.

For cooling:
![image](https://user-images.githubusercontent.com/11022970/220804965-d2d361ac-45eb-4640-a359-de5618e128e8.png)

For heating:
![image](https://user-images.githubusercontent.com/11022970/220805067-a6a46ef1-cad0-4799-a702-747d158bf4c5.png)

For evap:
![image](https://user-images.githubusercontent.com/11022970/220805166-fc1715c6-516e-4548-81d9-e0a582d0f47d.png)

Which ones would you map how? They can all be exposed, but what combination for each mode would constitute idle vs not idle?

**Comment by nathbullen** [comment]
Thanks for the super detailed response mate.

My understanding of HVAC systems in general is "calling for heat/cool" means that the temperature in the room has exceeded the set thresholds and the system is requesting hot/cold air to bring the temperature back into zone - which in my mind should mean that it's actively working to regulate the temp.

I think it'll depend a bit on some real world testing , but most logically to me, I think "calling for heat" should be the trigger to show heating as active. When it's not calling for heat, it should show as idle (unless the fan is still spinning, then show fan).

As for evap cooling, I think when the pump is on/operated it should show cooling but when the pump is off and the fan is on, it should show fan - evap cooling doesn't really have an idle mode. I don't think the cooler unit stays "busy" when it's cooling, but I actually don't know - I've only ever seen that pop up on the networker if I try and do things while it's prewetting.

Here's a simplified list of how I think it should behave - keen to hear what you think: 

Heating:
Calling for heat + fan on = heating
Not calling for heat + fan on = fan
Not calling for heat + fan off = idle

Evap:
Pump on + Fan on = cooling
Pump off + Fan on = fan

Cooling:
Same as heating^

**Comment by funtastix** [comment]
Check out 0.12.4

That'll now expose the "working mode"
