### ISSUE TITLE
setting the proper ClimateEntityFeature

### ISSUE THREAD

**Issue by grouts112** [funtastix/rinnaitouch#86]
WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.rinnaitouch.climate.RinnaiTouchZone'>) implements HVACMode(s): off, cool, heat, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/funtastix/rinnaitouch/issues

Running addon 0.12.14
Message seen in SYSLOG running ha core 2024.6.1

**Comment by kcaj-burr** [comment]
Hi,

I am encountering the same issue with a Rinnai Touch I just installed.

I am using a **NC-6** with a seriously old **Brivis ME 20e** - Gas ducted central heating unit - single zone

Currently the integration is not showing any data from the Rinnai Touch (though the Rinnai Touch app work fine).

Any thing I can help with to try and get this going?

**Comment by grouts112** [comment]
kcaj,  have you closed the Brivis wifi app?
the HA integration cant talk to the module if the App has the connection.

**Comment by kcaj-burr** [comment]
Sorry for the slow reply - yes I closed the app, but honestly I think our system might not be fully compatible.

If you see the screenshots of the app below, I get "???" on the fan only screen and zones and mode buttons are greyed out (assume they are not available on our old system). I dont even have the current temperature feedback in the Rinnai Touch app

I currently dont have time to dig into the issue in code, any thoughts?

Cheers 

![IMG_8188](https://github.com/user-attachments/assets/a525399f-797c-4ef5-a0d4-1eef39abd4ea)
![IMG_8186](https://github.com/user-attachments/assets/90272df5-70f6-432d-9f2b-68d4b0b5cc70)
![IMG_8187](https://github.com/user-attachments/assets/dcb1619e-3887-4f49-bd80-aa7134c3708b)

**Comment by benswinney** [comment]
#88

**Comment by funtastix** [comment]
> Submitted PR to fix the error posted by the original issue creator.
> 
> #88

Thanks for the PR, looks like there's a bit more work to do after upping the build deps. I'll look into that

**Comment by funtastix** [comment]
Looks like the build is fixed. I'll need to do some testing, then I can make a new release. Latest update is on the master branch.

**Comment by funtastix** [comment]
Testing done. Released : https://github.com/funtastix/rinnaitouch/releases/tag/0.12.15
